version: 2
jobs:
  build:
    docker:
      - image: openjdk:13-jdk-alpine
    steps:
      - checkout
      - run:
          name: Build application
          command: ./gradlew build
workflows:
  version: 2
  build_workflow:
    jobs:
      - build
